before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "test/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "test", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "test/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "test", "vendor"]
    php_mess_detector:
        enabled: true
        config:
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "test", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "test/*"]
    sensiolabs_security_checker: true
