sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
        - CHECK_CS=true
    - php: 7.2
      env:
        - DEPS=lowest
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
    - php: 7.2
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=latest
  allow_failures:
    - php: nightly

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - travis_retry composer install --no-interaction
  - composer show --installed

script:
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $EXECUTE_TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $EXECUTE_TEST_COVERAGE != 'true' ]]; then composer test ; fi
  - composer analyse

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; chmod +x ./docs/deploy.sh ; ./docs/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml ; fi
